@rootUrl = http://localhost:8080
# @rootUrl = https://serene-plains-38345.herokuapp.com
# @rootUrl = https://kjg2r2wpii.execute-api.us-east-1.amazonaws.com

get {{rootUrl}}/invoice

###
get {{rootUrl}}/invoice/0QzKlueng

###
post {{rootUrl}}/invoice
Content-Type: application/json

{
	"paymentDue": "2021-08-19T17:23:21.349752+05:00",
  "description": "Graphic Design",
  "paymentTerms": 10,
	"clientName": "John Wick",
	"clientEmail": "johnwick@mail.com",
	"status": "paid",
	"senderAddress": {
		"street": "19 Brooklyn",
		"city": "New York",
		"postCode": "E1 3EZ",
		"country": "USA"
	},
	"clientAddress": {
    "street": "19 Union Terrace",
    "city": "London ",
    "postCode": "E1 3EZ",
    "country": "United Kingdom"
	},
	"items": [
		{
			"name": "Brand Guidelines",
			"quantity": 1,
			"price": 1000,
			"total": 1000
		},
		{
      "name": "Email Design",
      "quantity": 2,
      "price": 200,
      "total": 400
		}
	]
}

###
put {{rootUrl}}/invoice/0QzKlueng
Content-Type: application/json

{
	"paymentDue": "2021-08-19T17:23:21.349752+05:00",
	"description": "graphic",
	"paymentTerms": 15,
	"clientName": "Sherlock Holmes",
	"clientEmail": "sherlock@mail.com",
	"status": "paid",
	"senderAddress": {
		"street": "221 Brooklyn",
		"city": "Brooklyn",
		"postCode": "E1 3EZ",
		"country": "USA",
		"isModified": true
	},
	"clientAddress": {
		"street": "221B Baker Street",
		"city": "London",
		"postCode": "NR24 5WQ",
		"country": "UK",
		"isModified": true
	},
	"items": {
		"createdItems": [
			{
				"name": "Design of smth",
				"quantity": 3,
				"price": 200,
				"total": 600
			}
		],
		"modifiedItems": [
			{
				"id": 7,
				"name": "just guidelines",
				"quantity": 1,
				"price": 1500,
				"total": 1500
			}
		],
		"deletedItems": [8]
	}
	
}

###
delete {{rootUrl}}/invoice/_Emijiqng
