@rootUrl = http://localhost:8080
# @rootUrl = https://serene-plains-38345.herokuapp.com

get {{rootUrl}}/invoice

###
get {{rootUrl}}/invoice/tEyIsgqng

###
post {{rootUrl}}/invoice
Content-Type: application/json

{
	"paymentDue": "2021-08-19T17:23:21.349752+05:00",
	"description": "Re-branding",
	"paymentTerms": 1,
	"clientName": "John Wick",
	"clientEmail": "johnwick@mail.com",
	"status": "paid",
	"senderAddress": {
		"street": "19 Brooklyn",
		"city": "New York",
		"postCode": "E1 3EZ",
		"country": "USA"
	},
	"clientAddress": {
		"street": "106 Kendell Street",
		"city": "Sharrington",
		"postCode": "NR24 5WQ",
		"country": "United Kingdom"
	},
	"items": [
		{
			"name": "Brand Guidelines",
			"quantity": 1,
			"price": 1800.90,
			"total": 1800.90
		},
		{
			"name": "car tax",
			"quantity": 1,
			"price": 200.10,
			"total": 200.10
		}
	],
	"total": 2000
}

###
put {{rootUrl}}/invoice/2180
Content-Type: application/json

{
	"paymentDue": "2021-08-19T17:23:21.349752+05:00",
	"description": "Re-branding",
	"paymentTerms": 1,
	"clientName": "John Wick",
	"clientEmail": "johnwick@mail.com",
	"status": "unpaid",
	"senderAddress": {
		"street": "19 Brooklyn",
		"city": "New York",
		"postCode": "E1 3EZ",
		"country": "USA"
	},
	"clientAddress": {
		"street": "106 Kendell Street",
		"city": "Sharrington",
		"postCode": "NR24 5WQ",
		"country": "United Kingdom"
	},
	"items": [
		{
			"name": "Brand Guidelines",
			"quantity": 1,
			"price": 1800.90,
			"total": 1800.90
		}
	],
	"total": 1800.90
}

###
delete {{rootUrl}}/invoice/3080
