version: '3.8'

services:
  database:
    env_file: config/dev.yml
    image: postgres
    container_name: postgres_db
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_HOST: ${DATABASE_HOST}
    restart: on-failure
  caching:
    env_file: config/dev.yml
    image: redis:7.0
    container_name: redis_store
    environment:
      REDIS_PORT_NUMBER: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: on-failure
    
volumes:
  postgresdb: null
