AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 128
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 5
    Tracing: Active

Resources:
  GetAllInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/getInvoices/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /invoice
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
    Metadata:
      BuildMethod: makefile

  GetInvoiceByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/getInvoiceById/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /invoice/{id}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
    Metadata:
      BuildMethod: makefile

  RemoveInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/removeInvoice/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /invoice/{id}
            Method: DELETE
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
    Metadata:
      BuildMethod: makefile

  ModifyInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/modifyInvoice/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /invoice/{id}
            Method: PUT
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
    Metadata:
      BuildMethod: makefile

  CreateInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/createInvoice/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /invoice
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
    Metadata:
      BuildMethod: makefile

# Outputs:
#   ApiUrl:
#     Description: "API Gateway endpoint URL"
#     Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
