PORT: "8080"

GRPC_HOST: "localhost"
GRPC_PORT: "8080"

DATABASE_HOST: "localhost"
DATABASE_DATABASE: "postgres"
DATABASE_USER: "postgres"
DATABASE_PORT: "5432"
DATABASE_PASSWORD: "postgres"
DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

REDIS_PORT: "6379"
REDIS_HOST: "localhost"
REDIS_PASSWORD: "password"
REDIS_ADDRESS: "localhost:6379"
REDIS_URL: "redis://:password@localhost:6379"
