PORT: "8080"

DATABASE_HOST: "localhost"
DATABASE_DATABASE: "postgres"
DATABASE_USER: "postgres"
DATABASE_PORT: "5432"
DATABASE_PASSWORD: "postgres"
DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
