PORT: "8080"

POSTGRES_HOST: "localhost"
POSTGRES_DATABASE: "postgres"
POSTGRES_USER: "postgres"
POSTGRES_PORT: "5432"
POSTGRES_PASSWORD: "postgres"
POSTGRES_URI: "postgres://postgres:postgres@localhost:5432/postgres"
